#!/bin/bash

# This is an example of a command-line script to run this utility.
# We make use of environment variables to work-around the lack of
# a mechanism for passing arguments to a script from the command-line.
# This is for UNIX-like systems only.

SCRIPT=$HOME/.blender/scripts/blender2haxe/HXExport.py

dir=Haxe
auto_skin=0
target=""

if [ ! $# -gt 0 ]; then
    echo "Example usage:"
    echo " blender2haxe target.blend"
    echo " blender2haxe --output <output_directory> target.blend"
    echo " blender2haxe --auto_skin target.blend"
    echo "   --output <output_directory>: sets where files will be put (default: Haxe)"
    echo "   --auto_skin: UV map images will be added upon need (slow)"
    exit 1
fi

while [ $# -gt 0 ]; do
  case $1
  in
    --output)
      dir=$2
      shift 2
    ;;

    --auto_skin|--autoskin)
      auto_skin=1
      shift
    ;;

    *)
      target=$1
      shift
    ;;
  esac
done

if [ "k$target" = "k" ]; then
    echo "No blender file supplied, aborting"
    exit 1
fi

echo "Working on $target"
echo "Working in $dir"
echo "Auto_skin set to $auto_skin"

BLENDER2HAXE_DIR=$dir BLENDER2HAXE_AUTO_SKIN=$auto_skin blender -b $target -P $SCRIPT


