#!/bin/bash

# This is an example of a command-line script to run this utility.
# We make use of environment variables to work-around the lack of
# a mechanism for passing arguments to a script from the command-line.
# This is for UNIX-like systems only.

SCRIPT=$HOME/.blender/scripts/blender2haxe/HXExport.py

dir=Haxe
target=""

if [ ! $# -gt 0 ]; then
    echo "Usage:"
    echo " blender2haxe -o <output_directory> target.blend"
    exit 1
fi

while [ $# -gt 0 ]; do
  case $1
  in
    -o)
      dir=$2
      shift 2
    ;;

    *)
      target=$1
      shift
    ;;
  esac
done

if [ "k$target" = "k" ]; then
    echo "No blender file supplied, aborting"
    exit 1
fi

echo "Working on $target"
echo "Working in $dir"

BLENDER2HAXE_DIR=$dir blender -b $target -P $SCRIPT


